export const menuData = {
  candidateCount: 10,
  categories: [
    {
      id: "mexican",
      name: "Mexican",
      weight: 2,
      meals: [
        { name: "Chimichangas", weight: 2, quick: false, bigMeal: false },
        { name: "Tacos", weight: 3, quick: true, bigMeal: true },
        { name: "Chili Cheese Burritos", weight: 3, quick: true, bigMeal: true },
        { name: "Fajitas", weight: 1, quick: true, bigMeal: true },
        { name: "Quesadillas", weight: 1, quick: true, bigMeal: true },
        { name: "Meximelt", weight: 2, quick: true, bigMeal: true },
        { name: "Mexican Pizza", weight: 1, quick: true, bigMeal: true },
      ],
    },
    {
      id: "asian",
      name: "Asian",
      weight: 2,
      meals: [
        { name: "Teriyaki Chicken", weight: 1, quick: true, bigMeal: true },
        { name: "Broccoli Chicken", weight: 1, quick: true, bigMeal: true },
        { name: "Sweet and Sour", weight: 1, quick: false, bigMeal: true },
        { name: "General Tso's Chicken", weight: 1, quick: false, bigMeal: true },
        { name: "Egg Rolls (Buffalo Chicken, Cheeseburger, etc.)", weight: 1, quick: false, bigMeal: false },
        { name: "Generic Stir Fry", weight: 1, quick: true, bigMeal: true },
      ],
    },
    {
      id: "italian",
      name: "Italian",
      weight: 2,
      meals: [
        { name: "Spaghetti", weight: 2, quick: true, bigMeal: true },
        { name: "Lazy Lasagna", weight: 2, quick: true, bigMeal: true },
        { name: "Chicken Parmesan", weight: 1, quick: false, bigMeal: true },
        { name: "Lasagna", weight: 1, quick: false, bigMeal: true },
        { name: "Goulash", weight: 2, quick: true, bigMeal: true },
        { name: "Pizza", weight: 3, quick: false, bigMeal: true },
        { name: "Ravioli", weight: 1, quick: true, bigMeal: true },
        { name: "Meatballs", weight: 1, quick: false, bigMeal: true },
      ],
    },
    {
      id: "country",
      name: "Country",
      weight: 3,
      meals: [
        { name: "Pinto Beans", weight: 2, quick: false, bigMeal: true },
        { name: "Fried Chicken", weight: 1, quick: false, bigMeal: false },
        { name: "Fish", weight: 1, quick: true, bigMeal: false },
        { name: "Meatloaf", weight: 3, quick: false, bigMeal: true },
        { name: "Beanie Weenies", weight: 2, quick: true, bigMeal: true },
        { name: "Turkey and Rice", weight: 2, quick: true, bigMeal: true },
        { name: "Country Fried Steak and Gravy (Dinner)", weight: 1, quick: false, bigMeal: false },
        { name: "Steak, Eggs, and Potatoes", weight: 2, quick: false, bigMeal: false },
        { name: "Ham Dinner w/ Fixings", weight: 1, quick: false, bigMeal: true },
      ],
    },
    {
      id: "meat-and-sides",
      name: "Meat and Sides",
      weight: 3,
      meals: [
        { name: "Pork Chops", weight: 2, quick: true, bigMeal: true },
        { name: "Steak", weight: 3, quick: true, bigMeal: false },
        { name: "Grilled Chicken", weight: 2, quick: true, bigMeal: true },
        { name: "London Broil", weight: 1, quick: false, bigMeal: true },
        { name: "Salisbury Steak", weight: 1, quick: false, bigMeal: true },
        { name: "Hawaiian Chicken", weight: 2, quick: false, bigMeal: true },
        { name: "New Meat and Sides Recipe", weight: 2, quick: false, bigMeal: false },
      ],
    },
    {
      id: "bbq",
      name: "BBQ",
      weight: 3,
      meals: [
        {
          name: "Pork Butt",
          weight: 2,
          quick: false,
          bigMeal: true,
          modifiers: [{ text: "with Hawgbacks", chance: 0.25 }],
        },
        { name: "Beef Brisket", weight: 1, quick: false, bigMeal: true },
        { name: "Ribs", weight: 1, quick: false, bigMeal: true },
        { name: "Smoked Chicken Wings", weight: 2, quick: false, bigMeal: true },
        { name: "Pork Loin", weight: 2, quick: false, bigMeal: true },
        { name: "Beer Chicken", weight: 2, quick: false, bigMeal: true },
        { name: "Shish Kebabs", weight: 2, quick: false, bigMeal: true },
        { name: "New BBQ Recipe", weight: 1, quick: false, bigMeal: false },
      ],
    },
    {
      id: "crock-pot-meals",
      name: "Crock Pot Meals",
      weight: 2,
      meals: [
        { name: "Roast", weight: 1, quick: false, bigMeal: true },
        { name: "Beef Stew", weight: 1, quick: false, bigMeal: true },
        { name: "Chili", weight: 1, quick: false, bigMeal: true },
        { name: "Tomato Soup", weight: 1, quick: false, bigMeal: true },
        { name: "Chicken and Dumplings", weight: 1, quick: false, bigMeal: true },
        { name: "Chicken Noodle Soup", weight: 1, quick: false, bigMeal: true },
        { name: "Potato Soup", weight: 1, quick: false, bigMeal: true },
      ],
    },
    {
      id: "skillet-meals",
      name: "Skillet Meals",
      weight: 3,
      meals: [
        { name: "Beef Stroganoff", weight: 1, quick: true, bigMeal: true },
        { name: "Sloppy Joes", weight: 1, quick: true, bigMeal: true },
        { name: "Mushroom Chicken", weight: 1, quick: true, bigMeal: true },
        { name: "Bratwurst Thing", weight: 1, quick: true, bigMeal: true },
        { name: "Skillet Pork Chops with Apples and Onion", weight: 1, quick: true, bigMeal: true },
        { name: "Beef Tenderloin in Mushroom Sauce", weight: 1, quick: false, bigMeal: false },
        { name: "Mexi-Mac Skillet", weight: 1, quick: true, bigMeal: true },
        { name: "New Skillet Meal Recipe", weight: 1, quick: false, bigMeal: false },
      ],
    },
    {
      id: "handhelds",
      name: "Handhelds",
      weight: 3,
      meals: [
        {
          name: "Hamburgers",
          weight: 3,
          quick: true,
          bigMeal: true,
          modifiers: [{ text: "(gourmet)", chance: 0.25 }],
        },
        {
          name: "Hot Dogs",
          weight: 3,
          quick: true,
          bigMeal: true,
          modifiers: [{ text: "(gourmet)", chance: 0.25 }],
        },
        { name: "Big Plate of Little Sandwiches", weight: 2, quick: true, bigMeal: true },
        { name: "Meatball Subs", weight: 1, quick: true, bigMeal: true },
        { name: "Hoagies", weight: 1, quick: true, bigMeal: true },
        { name: "Italian Sandwich Sub", weight: 1, quick: true, bigMeal: true },
        { name: "Junk Night", weight: 1, quick: true, bigMeal: false },
        { name: "French Dip", weight: 1, quick: false, bigMeal: true },
        { name: "Chicken Sandwiches", weight: 2, quick: true, bigMeal: true },
        { name: "Grilled Cheese", weight: 2, quick: true, bigMeal: true },
        { name: "Steak Sandwiches", weight: 1, quick: true, bigMeal: false },
      ],
    },
    {
      id: "cajun",
      name: "Cajun",
      weight: 1,
      meals: [
        { name: "Shrimp Boil", weight: 1, quick: false, bigMeal: true },
        { name: "Cajun Pasta Salad", weight: 1, quick: false, bigMeal: true },
        { name: "Gumbo", weight: 1, quick: false, bigMeal: true },
        { name: "Jambalaya", weight: 1, quick: false, bigMeal: true },
        { name: "Red Beans and Rice", weight: 1, quick: false, bigMeal: true },
        { name: "Dirty Rice", weight: 1, quick: true, bigMeal: true },
        { name: "Bourbon Street Chicken and Shrimp", weight: 1, quick: true, bigMeal: true },
      ],
    },
    {
      id: "casseroles",
      name: "Casseroles",
      weight: 2,
      meals: [
        { name: "Chicken Pot Pie", weight: 1, quick: false, bigMeal: true },
        { name: "Chicken Casserole", weight: 1, quick: false, bigMeal: true },
        { name: "Hamburger Helper", weight: 1, quick: true, bigMeal: true },
        { name: "Misc New Casseroles", weight: 1, quick: false, bigMeal: true },
        { name: "Tater Tot Casserole", weight: 1, quick: false, bigMeal: true },
      ],
    },
    {
      id: "fast-food",
      name: "Fast Food",
      weight: 2,
      meals: [
        { name: "Arby's Sandwiches", weight: 1, quick: true, bigMeal: true },
        { name: "Krystals", weight: 1, quick: true, bigMeal: true },
        { name: "Giant McRib", weight: 1, quick: false, bigMeal: true },
        { name: "Poor Man Monte Cristo", weight: 1, quick: true, bigMeal: false },
        { name: "New Fast Food Recipe", weight: 1, quick: false, bigMeal: false },
      ],
    },
    {
      id: "breakfast",
      name: "Breakfast",
      weight: 2,
      meals: [
        { name: "Chicken and Waffles", weight: 1, quick: false, bigMeal: true },
        { name: "Waffles", weight: 3, quick: true, bigMeal: true },
        { name: "Pancakes", weight: 3, quick: true, bigMeal: true },
        { name: "Biscuits and Gravy", weight: 3, quick: true, bigMeal: true },
        { name: "Country Fried Steak and Gravy (Breakfast)", weight: 1, quick: false, bigMeal: false },
      ],
    },
    {
      id: "seafood",
      name: "Seafood",
      weight: 1,
      meals: [
        { name: "Fried Fish", weight: 2, quick: false, bigMeal: false },
        { name: "Salmon", weight: 1, quick: true, bigMeal: false },
        { name: "Grilled Fish", weight: 2, quick: true, bigMeal: true },
        { name: "Fish Tacos", weight: 2, quick: true, bigMeal: true },
        { name: "Surf and Turf", weight: 1, quick: false, bigMeal: false },
        { name: "New Seafood Recipe", weight: 1, quick: false, bigMeal: false },
      ],
    },
    {
      id: "salad",
      name: "Salad",
      weight: 1,
      meals: [
        { name: "Steak Salad", weight: 2, quick: true, bigMeal: false },
        { name: "Grilled Chicken Salad", weight: 2, quick: true, bigMeal: true },
        { name: "House Salad", weight: 1, quick: true, bigMeal: false },
        { name: "Taco Salad", weight: 2, quick: true, bigMeal: true },
      ],
    },
    {
      id: "new-recipe",
      name: "New Recipe",
      weight: 2,
      result: "New Recipe",
      quick: false,
      bigMeal: false,
    },
    {
      id: "new-category",
      name: "New Category",
      weight: 1,
      result: "New Category",
      quick: false,
      bigMeal: false,
    },
  ],
};